spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 1234

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
